Feature/wrapper
MetaCell/open-physiology-viewer pull request #1
Opened 2021-05-25 12:09 UTC by ddelpiano

Wrapper implementation:

- wrapper/bin/converter: quite minimal script that instantiate the conversion handler and get id/file and method.
- wrapper/bin/model/filehandler: generic class that iterate through all the format supported and go step by step in the conversion, plus there is the id retrieval from google sheet.
- All the logic that required to interact with the pre-existent model has been implemented in modelClasses, where I have kind of deserialiser for each step of the conversion required.

Known issue: right now I can still see few discrepancy from generated to JsonLD, still trying to assess them.

2021-05-25 15:28 UTC, zsinnema commented on wrapper/bin/model/filehandler.js
> +                let _json_model = converter.fromXLSXToJson(_xlsx);
const?

2021-05-25 15:28 UTC, zsinnema commented on wrapper/bin/model/filehandler.js
> +                let _xlsx = fs.readFileSync(file, 'binary');
const?

2021-05-25 15:28 UTC, zsinnema commented on wrapper/bin/model/filehandler.js
> +                    let _flattened = JSON.stringify(res, null, 2);
const

2021-05-25 15:28 UTC, zsinnema commented on wrapper/bin/model/filehandler.js
> +        var startConverting = false;
let

2021-05-25 16:58 UTC, tgbugs commented on wrapper/package.json
> +  "license": "ISC",
Can this be Apache2? re: https://github.com/open-physiology/open-physiology-viewer/issues/66

2021-05-25 17:25 UTC, tgbugs commented
Two requests and two issues I have encountered while testing.

Requests.
1. Rename `-m --method` to `-f --from` and add an option `-t --to` which will output only the single stage of conversion. If `-t` is not specified then a folder with all the subsequent formats is produced as it is now.
2. Can we get a `-o --output` option that specifies the name of the output file or folder?

For the issues, both were resolved by commenting out the offending variables. I'm not sure why those were being pulled in to the top level.

```
/home/tom/git/open-physiology-viewer/dist/converter.js:5
/******/ 	var parentHotUpdateCallback = window["webpackHotUpdate"];
         	                              ^

ReferenceError: window is not defined
    at /home/tom/git/open-physiology-viewer/dist/converter.js:5:41
    at Object.<anonymous> (/home/tom/git/open-physiology-viewer/dist/converter.js:860:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/tom/git/open-physiology-viewer/wrapper/bin/model/filehandler.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

```
/home/tom/git/open-physiology-viewer/dist/converter.js:61308
const crypto = self.crypto || self.msCrypto;
               ^

ReferenceError: self is not defined
    at Object.../node_modules/rdf-canonize/lib/MessageDigest-browser.js (/home/tom/git/open-physiology-viewer/dist/converter.js:61308:16)
    at __webpack_require__ (/home/tom/git/open-physiology-viewer/dist/converter.js:783:30)
    at fn (/home/tom/git/open-physiology-viewer/dist/converter.js:94:20)
    at Object.<anonymous> (/home/tom/git/open-physiology-viewer/dist/converter.js:61870:23)
    at Object.../node_modules/rdf-canonize/lib/URDNA2015.js (/home/tom/git/open-physiology-viewer/dist/converter.js:62375:30)
    at __webpack_require__ (/home/tom/git/open-physiology-viewer/dist/converter.js:783:30)
    at fn (/home/tom/git/open-physiology-viewer/dist/converter.js:94:20)
    at Object.../node_modules/rdf-canonize/lib/index.js (/home/tom/git/open-physiology-viewer/dist/converter.js:63121:19)
    at __webpack_require__ (/home/tom/git/open-physiology-viewer/dist/converter.js:783:30)
    at fn (/home/tom/git/open-physiology-viewer/dist/converter.js:94:20)

```

2021-05-28 08:59 UTC, ddelpiano commented
> Two requests and two issues I have encountered while testing.
> 
> Requests.
> 
> 1. Rename `-m --method` to `-f --from` and add an option `-t --to` which will output only the single stage of conversion. If `-t` is not specified then a folder with all the subsequent formats is produced as it is now.
> 2. Can we get a `-o --output` option that specifies the name of the output file or folder?
> 
> For the issues, both were resolved by commenting out the offending variables. I'm not sure why those were being pulled in to the top level.
> 
> ```
> /home/tom/git/open-physiology-viewer/dist/converter.js:5
> /******/ 	var parentHotUpdateCallback = window["webpackHotUpdate"];
>          	                              ^
> 
> ReferenceError: window is not defined
>     at /home/tom/git/open-physiology-viewer/dist/converter.js:5:41
>     at Object.<anonymous> (/home/tom/git/open-physiology-viewer/dist/converter.js:860:10)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/home/tom/git/open-physiology-viewer/wrapper/bin/model/filehandler.js:3:19)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
> ```
> 
> ```
> /home/tom/git/open-physiology-viewer/dist/converter.js:61308
> const crypto = self.crypto || self.msCrypto;
>                ^
> 
> ReferenceError: self is not defined
>     at Object.../node_modules/rdf-canonize/lib/MessageDigest-browser.js (/home/tom/git/open-physiology-viewer/dist/converter.js:61308:16)
>     at __webpack_require__ (/home/tom/git/open-physiology-viewer/dist/converter.js:783:30)
>     at fn (/home/tom/git/open-physiology-viewer/dist/converter.js:94:20)
>     at Object.<anonymous> (/home/tom/git/open-physiology-viewer/dist/converter.js:61870:23)
>     at Object.../node_modules/rdf-canonize/lib/URDNA2015.js (/home/tom/git/open-physiology-viewer/dist/converter.js:62375:30)
>     at __webpack_require__ (/home/tom/git/open-physiology-viewer/dist/converter.js:783:30)
>     at fn (/home/tom/git/open-physiology-viewer/dist/converter.js:94:20)
>     at Object.../node_modules/rdf-canonize/lib/index.js (/home/tom/git/open-physiology-viewer/dist/converter.js:63121:19)
>     at __webpack_require__ (/home/tom/git/open-physiology-viewer/dist/converter.js:783:30)
>     at fn (/home/tom/git/open-physiology-viewer/dist/converter.js:94:20)
> ```

Hi @tgbugs , sure I will implement 1. and 2.

The issue you had with self and window has been solved already, when I did the cleanup I removed some global declarations that I should have kept in the wrapper, thx for spotting it.

2021-06-02 14:44 UTC, zsinnema requested changes

2021-06-02 14:44 UTC, zsinnema commented on src/model/modelClasses.js
> +            let [obj, key] = refs[0];
please (everywhere) use const instead of let for non changing values

2021-06-02 14:44 UTC, zsinnema commented on src/model/modelClasses.js
> +                    let fullID = getFullID(namespace, e.id);
there is no need to create the fullId variable

2021-06-02 14:44 UTC, zsinnema commented on src/model/modelClasses.js
> +            let resources = added.filter(id => entitiesList[getFullID(namespace,id)].class !== $SchemaClass.External);
what is the use of this resources?

2021-06-02 14:44 UTC, zsinnema commented on src/model/modelClasses.js
> +            const resources = added.filter(id => entitiesList[getFullID(namespace,id)].class !== $SchemaClass.External);
what is the use of the resources and externals?

2021-06-14 11:23 UTC, ddelpiano commented on src/model/modelClasses.js
> +                    let fullID = getFullID(namespace, e.id);
fullID is used the line below and key for entitiesById map

2021-06-14 12:01 UTC, zsinnema approved these changes
lgtm

2021-06-14 12:03 UTC, merged