Feature/13 - Fixes scrollbar misalignment
MetaCell/open-physiology-viewer pull request #14
Opened 2021-07-23 01:49 UTC by jrmartin

Removes scrollbar from canvas element, not needed to scroll canvas.

2021-07-23 07:05 UTC, zsinnema requested changes

2021-07-23 07:05 UTC, zsinnema commented on src/test-app/app.js
> +            margin-top: 1vh;
why not stick the footer to the bottom like:
```
position: absolute;
bottom: 0;
width: 100%;
```

2021-07-26 14:14 UTC, zsinnema approved these changes
lgtm

2021-07-26 14:14 UTC, merged

2021-07-31 23:03 UTC, tgbugs commented
@jrmartin I think this removed the scroll bars that are in the resources tab so it is no longer possible to scroll through the tables in that tab.

2021-08-01 23:05 UTC, jrmartin commented
@tgbugs I reopened the PR with a fix for it #27. This branch is not based on the open PR with all the fixes you did to merge the different PR's yet (branch : tgbugs/big-merge), we haven't sync that one yet #26.

I can open a PR to tgbugs/big-merge with the fix too if you prefer.