Fixed layout issue on repository panel
MetaCell/open-physiology-viewer pull request #24
Opened 2021-07-30 13:08 UTC by enicolasgomez

Changed repository browser's layout to absolute position with a z-index = 100 so it overlays the canvas without replacing it

2021-07-30 14:22 UTC, zsinnema requested changes

2021-07-30 14:22 UTC, zsinnema commented on src/test-app/app.js
> +            <section id="repo-panel" *ngIf="showRepoPanel" class="w3-quarter w3-gray w3-border-right w3-border-white" style="position:absolute; z-index: 100;">
we should use style on an element... please move it to the css file

2021-07-30 14:22 UTC, zsinnema commented on src/test-app/app.js
> +            <section id="repo-panel" *ngIf="showRepoPanel" class="w3-quarter w3-gray w3-border-right w3-border-white" style="position:absolute; z-index: 100;">
also I don't like the vertical scrollbarr appearing when the list is populated

2021-08-01 08:17 UTC, zsinnema commented on src/test-app/app.js
> +            <section id="repo-panel" *ngIf="showRepoPanel" class="w3-quarter w3-gray w3-border-right w3-border-white" style="position:absolute; z-index: 100;">
imo the issue should be fixed on the main-panel and not in the repo-panel:
```
#main-panel[_ngcontent-ukd-c0] mat-tab-group[_ngcontent-ukd-c0] {
    height: inherit;
    /* width: calc(100%); */
}
```
by removing/commenting the width

2021-08-04 12:15 UTC, enicolasgomez commented on src/test-app/app.js
> +            <section id="repo-panel" *ngIf="showRepoPanel" class="w3-quarter w3-gray w3-border-right w3-border-white" style="position:absolute; z-index: 100;">
Changed and pushed as requested. Please verify.

2021-08-04 17:59 UTC, zsinnema approved these changes

2021-08-04 17:59 UTC, merged