Issue/31 3D Scene consuming 100% CPU resources
MetaCell/open-physiology-viewer pull request #32
Opened 2021-08-19 19:33 UTC by enicolasgomez

Improvements related to the mentioned fix

2021-08-24 18:53 UTC, jrmartin requested changes
It looks good @enicolasgomez and works locally. 

Made a few requests to remove some commented out code we don't need.

2021-08-24 18:53 UTC, jrmartin commented on src/components/webGLScene.js
> +        //window.__Zone_disable_requestAnimationFrame = true;
We can probably delete this commented out code.

2021-08-24 18:53 UTC, jrmartin commented on src/components/webGLScene.js
> +      if (performance.now() - this.lastNow < 1000/30) return true;
Instead of hard-coding 1000/300, would be more useful to store it in global constant.

2021-08-24 18:53 UTC, jrmartin commented on src/components/webGLScene.js
> +        //if (this.skipRender()) return;
This commented out code can be removed too.

2021-08-24 18:53 UTC, jrmartin commented on src/test-app/app.js
> +            //width : calc(100% - 48px);
Remove commented out code if we are not using it.

2021-09-03 12:41 UTC, enicolasgomez commented on src/components/webGLScene.js
> +        //if (this.skipRender()) return;
I left that one opened in case @zsinnema wants to add the throttling code

2021-09-03 19:08 UTC, tgbugs commented
Please my feedback/notes on https://github.com/tgbugs/open-physiology-viewer/pull/1.

2022-04-08 22:39 UTC, jrmartin commented
@enicolasgomez Can you close this PR and reopen it against development? Might be easier too to create a new branch based from development, and add manually the changes. Otherwise the history commits will mess up what's on development currently when we merge.

2022-04-11 12:11 UTC, enicolasgomez commented
Closing. Re opening it against develop.

2022-04-11 12:11 UTC, closed without merging