Feature/3 some performance optimalisations
MetaCell/open-physiology-viewer pull request #4
Opened 2021-07-14 14:24 UTC by zsinnema

2021-07-15 06:36 UTC, zsinnema commented
please enable chrome://flags/#enable-gpu-rasterization

2021-07-26 09:17 UTC, ddelpiano requested changes

2021-07-26 09:17 UTC, ddelpiano commented on src/model/chainModel.js
> +            for (let i = 1; i < N; i++){
why don't merge these 2 loops into a single one?

2021-07-26 09:17 UTC, ddelpiano commented on src/model/chainModel.js
> +            let targetInternal = (i === N - 1) || sameAsNext && !sameAsPrev;
these 4 variables to const?

2021-07-26 09:17 UTC, ddelpiano commented on src/model/graphModel.js
> +            let noAxisLyphs = (res.lyphs||[]).filter(lyph => lyph::isObject() && !lyph.conveys && !lyph.layerIn && !lyph.isTemplate);
noAxisLyphsInternal and noAxisLyphs to const?

2021-07-26 09:17 UTC, ddelpiano commented on src/model/graphModel.js
> +                    console.log(link);
since the logger is already used, do we need the console.log as well?

2021-07-26 09:17 UTC, ddelpiano commented on src/model/graphModel.js
> +                    console.log(link);
same here

2021-07-26 16:28 UTC, merged