implemented selection and zfighting improvements
MetaCell/open-physiology-viewer pull request #66
Opened 2021-11-04 15:17 UTC by enicolasgomez

- removed obj main array maintaniance for selection as there's no need to identify which objects are main
- applied z-fighting selection algorithm to regions

@zsinnema about using a Set instead of array, when going over the code realized that I don't want the value or key of the  sphere's volume, just the index which results on the z-layer position (multiplied by -0.05 actually so the design look is not affected) so couldn't find a fit for Set() finally.

as both issues are closed related created only 1 branch

2021-11-08 22:06 UTC, jrmartin requested changes
@enicolasgomez The selection and z fighting looks good and works well.

Resizing of regions and dragging objects functionality seems to be lost though. Can you take a look what may have broken it on this branch please?

https://user-images.githubusercontent.com/4562825/140825683-2f368566-a937-40ac-bd6b-f10b3c39b5d0.mp4

2021-11-15 16:38 UTC, enicolasgomez commented
@jrmartin should be fixed now, please give it a try.

2021-11-15 17:08 UTC, jrmartin approved these changes

2021-11-15 17:09 UTC, jrmartin commented
Looks good to me, I tested locally and it's working as expected. If it's good with you too @zsinnema , we can merge it.

2021-11-18 12:23 UTC, merged